export enum CARD_TYPE {
	VISA = "VISA",
	MASTERCARD = "MASTERCARD",
	HUMO = "HUMO",
	UZCARD = "UZCARD",
}

export enum TRANSACTION_TYPE {
	DEPOSIT = "DEPOSIT",
	WITHDRAWAL = "WITHDRAWAL",
	TRANSFER = "TRANSFER",
	P2P = "P2P",
}

export enum TRANSACTION_STATUS {
	PENDING = "PENDING",
	SUCCESS = "SUCCESS",
	FAILED = "FAILED",
	CANCELLED = "CANCELLED",
}
